services:
  gateway:
    build: .
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge