server:
  port: 8081

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: core-service
          uri: http://31.129.99.69:8080
          predicates:
            - Path=/api/operation/**,/api/account/**,/api/currency/**, /api/fcm/**
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: INTERNAL_SERVER_ERROR, BAD_GATEWAY, SERVICE_UNAVAILABLE
                methods: GET,POST,PUT
                backoff:
                  firstBackoff: 100ms
                  maxBackoff: 1s
                  factor: 2
                  basedOnPreviousValue: false
            - name: CircuitBreaker
              args:
                name: coreServiceCB
                fallbackUri: forward:/fallback/core
                statusCodes: INTERNAL_SERVER_ERROR, BAD_GATEWAY
        - id: user-service
          uri: http://194.59.186.122:8080
          predicates:
            - Path=/register/**, /login/**, /refresh/**, /logout/**, /role/**, /users/**, /profile/**
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: INTERNAL_SERVER_ERROR, BAD_GATEWAY, SERVICE_UNAVAILABLE
                methods: GET,POST,PUT
                backoff:
                  firstBackoff: 100ms
                  maxBackoff: 1s
                  factor: 2
                  basedOnPreviousValue: false
            - name: CircuitBreaker
              args:
                name: userServiceCB
                fallbackUri: forward:/fallback/user
                statusCodes: INTERNAL_SERVER_ERROR, BAD_GATEWAY
        - id: loan
          uri: http://194.59.186.122:8040
          predicates:
            - Path=/api/loan/**
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: INTERNAL_SERVER_ERROR, BAD_GATEWAY, SERVICE_UNAVAILABLE
                methods: GET,POST,PUT
                backoff:
                  firstBackoff: 100ms
                  maxBackoff: 1s
                  factor: 2
                  basedOnPreviousValue: false
            - name: CircuitBreaker
              args:
                name: userLoanCB
                fallbackUri: forward:/fallback/loan

resilience4j.circuitbreaker:
  instances:
    userServiceCB:
      failureRateThreshold: 50
      minimumNumberOfCalls: 5
      slidingWindowSize: 10
      waitDurationInOpenState: 10s
      automaticTransitionFromOpenToHalfOpenEnabled: true
logging:
  level:
    org.springframework.cloud.gateway: TRACE