// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using patterns_settings.Data;

#nullable disable

namespace patterns_settings.Migrations
{
    [DbContext(typeof(SettingsDbContext))]
    partial class SettingsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("patterns_settings.Models.AdminClientSettings", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Theme")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.ToTable("AdminClientSettings");
                });

            modelBuilder.Entity("patterns_settings.Models.BankClientSettings", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<Guid>>("HiddenAccounts")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<int>("Theme")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.ToTable("BankClientSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
