spring:
  datasource:
    url: ${JDBC_URL:jdbc:postgresql://localhost:5432/patterns}
    username: ${JDBC_USER:postgres}
    password: ${JDBC_PASSWORD:postgres}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/dbchangelog.xml
  rabbitmq:
    host: 194.59.186.122
    username: guest
    password: guest
    queues:
      operation: operation
      operation-reply: operationReply
      loan: GetLoan
      user-info: userinfo
      user-info-reply: userInfoResponseQueue
security:
  jwt:
    secret: "somejwttokenlmaosomejwttokenlmaosomejwttokenlmaosomejwttokenlmao"