spring:
  datasource:
    url: ${JDBC_URL:jdbc:postgresql://31.129.99.69:5430/patterns}
    username: ${JDBC_USER:postgresss}
    password: ${JDBC_PASSWORD:postgresss}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/dbchangelog.xml
  rabbitmq:
    host: 194.59.186.122
    username: guest
    password: guest
    queues:
      operation: operation
      operation-reply: operationReply
      loan: GetLoan
      user-info: userinfo
      user-info-reply: userInfoResponseQueue
security:
  jwt:
    secret: "somejwttokenlmaosomejwttokenlmaosomejwttokenlmaosomejwttokenlmao"
firebase:
  credentials:
    path: classpath:patterns3-firebase-adminsdk-fbsvc-1dc3cc4950.json